[package]
name = "character_location_map"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown = "1.0.0-alpha.17"
xml = "0.8.20"

[[bin]]
name = "character_location_map"
path = "src/main.rs"
